// mobile.html 스크립트 런타임 스모크 (브라우저 없는 대체 검증). 실행: node tests/smoke_mobile.mjs
import { readFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
const here = dirname(fileURLToPath(import.meta.url));
const html = readFileSync(join(here, "..", "server", "static", "mobile.html"), "utf8");
const js = html.match(/<script>([\s\S]*?)<\/script>/)[1].replace("load(); setInterval(load, 6000);", "");
const store = { "tt-m-me": "me@x" }; globalThis.localStorage = { getItem: k => store[k] ?? null, setItem: (k, v) => store[k] = v };
const els = {};
globalThis.document = { querySelector: s => els[s] ?? (els[s] = { innerHTML: "", textContent: "", classList: { add(){}, remove(){}, toggle(){}, contains: () => false } }) };
globalThis.CSS = { escape: s => s };
const two = [{ id: "A1", state: "todo", title: "t", labels: [] }, { id: "B2", state: "review", title: "r", labels: [], version: 1 },
  { id: "M3", state: "in_progress", title: "mine", labels: [], assignee: "me@x" }, { id: "O4", state: "in_progress", title: "other", labels: [], assignee: "someone" }];
let n = 0;
globalThis.fetch = async () => ({ ok: true, json: async () => structuredClone(n++ < 2 ? two : [{ id: "M3", state: "in_progress", title: "mine", labels: [], assignee: "me@x", lease_by: "me@x", lease_expires: new Date(Date.now()+36e5).toISOString().slice(0,19)+"+0000" }, { id: "E5", state: "in_progress", title: "expired", labels: [], assignee: "other@gx", lease_by: "other@gx", lease_expires: "2026-01-01T00:00:00+0900" }, { id: "O4", state: "in_progress", title: "nolease", labels: [], assignee: "someone" }]) });
(0, eval)(js);
const { load, pick } = globalThis;
await load();
if (!els["#list"].innerHTML.includes("B2")) throw new Error("1st render broken");
const before = els["#list"].innerHTML;
await load();
if (els["#list"].innerHTML !== before) throw new Error("identical data re-rendered");
await load();
if (!els["#list"].innerHTML.includes("empty")) throw new Error("3rd render not applied");
await load();
pick("in_progress");
const list = els["#list"].innerHTML;
if (!list.includes("class=\"card mine\"")) throw new Error("mine class missing: "+list.slice(0,150));
if (list.includes("O4")) throw new Error("no-lease card shown in 청구중 default");
if (!list.includes("잔여")) throw new Error("lease left tag missing");
setSub("all");
if (!els["#list"].innerHTML.includes("O4") || !els["#list"].innerHTML.includes("class=\"card other\"")) throw new Error("all-sub missing other card");
if (!list.includes("리뷰 요청")) throw new Error("mine card lacks actions");
if (!list.includes("E5") || !list.includes("lease 만료")) throw new Error("만료 점유가 청구중에서 누락");
if (list.includes("O4")) throw new Error("lease 없는 카드는 전체에만");
setSub("all");
if (!els["#list"].innerHTML.includes("O4")) throw new Error("all에서 O4 누락");
setSub("lease");
console.log("smoke ok");
